### ISSUE TITLE
Deply failure : "CompleteTest failure,"

### ISSUE THREAD

**Issue by deangraham** [paull10au/qsyd_InvocableEmailActions#8] opened 2020-07-22 13:50 UTC
When trying to deply to SFDC it said completed and then these errors. Any help is appreciated. 

Deployment CompleteTest failure, method: qsyd_InvocableEmailActionTest.given_requiredEmailParametersAreProvided_when_anEmailIsInstantiated_then_anEmailIsSent -- qsyd_InvocableEmailBase.InvocableEmailException: >>> qsyd_InvocableEmailAction.sendEmail failed with exception: >>> Exception executing qsyd_InvocableEmailBase.send: ((1) : INVALID_CROSS_REFERENCE_KEY : invalid cross reference id) stack Class.qsyd_InvocableEmailAction: line 67, column 1
Class.qsyd_InvocableEmailActionTest.given_requiredEmailParametersAreProvided_when_anEmailIsInstantiated_then_anEmailIsSent: line 66, column 1

Test failure, method: qsyd_InvocableEmailTemplateActionTest.given_requiredEmailParametersAreProvided_when_anEmailIsInstantiated_then_anEmailIsSent -- qsyd_InvocableEmailBase.InvocableEmailException: >>> qsyd_InvocableEmailTemplateAction.sendEmail failed with exception: >>> Exception executing qsyd_InvocableEmailBase.send: ((1) : INVALID_CROSS_REFERENCE_KEY : invalid cross reference id) stack Class.qsyd_InvocableEmailTemplateAction: line 63, column 1
Class.qsyd_InvocableEmailTemplateActionTest.given_requiredEmailParametersAreProvided_when_anEmailIsInstantiated_then_anEmailIsSent: line 59, column 1

**Comment by Staples1887** [comment] 2020-09-29 14:01
This is caused by the object IDs in the tests.

For example from qsyd_InvocableEmailActions\src\classes\qsyd_InvocableEmailTemplateActionTest.cls (Line 21):
`    Private Static final String CONTACT_EXAMPLE = '0030J00002ThBGcQAN';
`

This would be solved using a [stub](https://trailhead.salesforce.com/content/learn/modules/unit-testing-on-the-lightning-platform/mock-stub-objects)

[This might also help](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_methods_system_test.htm#apex_System_Test_createStub)

Another option is to fork this repository, change the ids to record in your org, then deploy that to salesforce.

I hope this helps

**Comment by dbrobes** [comment] 2021-02-11 19:52
Was this issue able to be resolved in the original code without forking? I'm a bit new to all of this, and installed this in a Sandbox environment without issue, but ran into this problem trying to install it in production. It works awesome in the sandbox environment.

**Comment by paull10au** [comment] 2021-02-13 09:01
Thank you @Staples1887, @stjenkins13 and all who have used this.

@deangraham, @dbrobes - I have updated the test classes to create their own test records

Please let me know if you still does not work for you.

One caveat, the test classes create these records use minimal data so make sure you have no automation (triggers, pb, flows) that rely on specific data. otherwise you may need to adjust.

Also if any test objects involve callouts, you will need to adjust to test for "test" context.

**Closed as completed by paull10au** 2021-02-13 09:01 UTC

**Comment by dbrobes** [comment] 2021-02-13 13:06
Paul, thanks for all of your work on this package - it is really
incredible.
